---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "00:00"
    labels:
      - "dependencies"
  - package-ecosystem: npm
    directory: /api/package.json
    schedule:
      interval: weekly
      day: monday
      time: "00:00"
  - package-ecosystem: npm
    directory: /inventory/package.json
    schedule:
      interval: weekly
      day: monday
      time: "00:00"
  - package-ecosystem: npm
    directory: /recommendations/package.json
    schedule:
      interval: weekly
      day: monday
      time: "00:00"
  - package-ecosystem: npm
    directory: /spa/package.json
    schedule:
      interval: weekly
      day: monday
      time: "00:00"
