services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./mongo-seed:/docker-entrypoint-initdb.d
    restart: unless-stopped
    environment:
      - SEED_FILE=${PRODUCT_TYPE}Products.json