/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    InventoryComponent: typeof import('./src/components/InventoryComponent.vue')['default']
    NavBarComponent: typeof import('./src/components/NavBarComponent.vue')['default']
    ProductsGridComponent: typeof import('./src/components/ProductsGridComponent.vue')['default']
    ProductsGridItemComponent: typeof import('./src/components/ProductsGridItemComponent.vue')['default']
    ProductsListComponent: typeof import('./src/components/ProductsListComponent.vue')['default']
    ProductsListItemComponent: typeof import('./src/components/ProductsListItemComponent.vue')['default']
    RecommendationsComponent: typeof import('./src/components/RecommendationsComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowJWTComponent: typeof import('./src/components/ShowJWTComponent.vue')['default']
    SignInButton: typeof import('./src/components/SignInButton.vue')['default']
    SignOutButton: typeof import('./src/components/SignOutButton.vue')['default']
    WelcomeNameComponent: typeof import('./src/components/WelcomeNameComponent.vue')['default']
  }
}
